@baseUri = http://localhost:8182/api

### Index
GET {{baseUri}}/categories HTTP/1.1
Content-Type: application/json

### Store
POST {{baseUri}}/categories HTTP/1.1
Content-Type: application/json

{
    "name": "Categoria Nova11",
    "description": "Categoria criada usando CategoryStoreRequest via API/REST11"
}


### Show
# 123 é o ID da categoria neste exemplo.
#Utilize um ID existente em sua base de dados.
GET {{baseUri}}/categories/9 HTTP/1.1
Content-Type: application/json


### Update
# 123 é o ID da categoria neste exemplo.
#Utilize um ID existente em sua base de dados.
PUT {{baseUri}}/categories/2 HTTP/1.1
Content-Type: application/json

{
    "name": "Categoria ATUALIZADA via CategoryUpdateRequest API/REST11",
    "description": "Categoria ATUALIZADA via CategoryUpdateRequest API/REST11"
}

### Delete
# 123 é o ID da categoria neste exemplo.
#Utilize um ID existente em sua base de dados.
DELETE {{baseUri}}/categories/10 HTTP/1.1
Content-Type: application/json
